---
- name: Install some packages
  hosts: localhost
  become: yes
  tasks:
          - name: install multiple packages
            ansible.builtin.yum:
                    name: "{{item}}"
                    state: present
            loop:
                    - httpd
            
                    
